name: Build Windows executable

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows-based runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository
      - name: Set up Python  # Ensure Python is installed
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the desired Python version
      - name: Install PyInstaller  # Install PyInstaller
        run: pip install pyinstaller
      - name: Install Requirements  # Install requirements
        run: pip install -r requirements.txt
      - name: Build executable
        run: pyinstaller --onefile gui.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/gui.exe  # Path to the built executable
